language: python
python:
    - "3.6"
cache: pip
addons:
  apt:
    packages:
    - jq

before_install:
  - yes | pip install fandogh_cli --upgrade
script:
  - ./manage.py test

deploy:
  provider: script
  script: bash deployment/scripts/deploy-to-fandogh.sh
  on:
    branch: master
